language: go

install:
  - mkdir -p ${GOPATH}/src/github.com/Juniper
  - (cd ${GOPATH}/src/github.com/Juniper && git clone https://github.com/Juniper/contrail-go-api -b 1.0.0)
  - wget https://github.com/Juniper/contrail-go-api/releases/download/1.0.0/contrail-go-api-generated-types-r2.20.tar.gz
  - tar -zxvf contrail-go-api-generated-types-r2.20.tar.gz -C ${GOPATH}/src
  - mkdir -p ${GOPATH}/src/github.com/GoogleCloudPlatform
  - (cd ${GOPATH}/src/github.com/GoogleCloudPlatform && git clone https://github.com/GoogleCloudPlatform/kubernetes.git -b v1.0.2)

script: GOPATH=${GOPATH}:${GOPATH}/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace go test ./...
